### ISSUE TITLE
Uses deprecated pylint.__pkginfo__.numversion

### ISSUE THREAD

**Issue by kevinoid** [edaniszewski/pylint-quotes#23]
pylint-quotes does not work with pylint 2.8.0 due to the removal of `numversion` from `__pkginfo__` in https://github.com/PyCQA/pylint/commit/fbcb27acb3431cea846bbfb997f411e51417d1bb.  To demonstrate:

```sh
pip3 install pylint==2.8.0 pylint-quotes
pylint --load-plugins pylint_quotes example.py 
```

Produces

    Traceback (most recent call last):
      File "/path/to/venv/bin/pylint", line 8, in <module>
        sys.exit(run_pylint())
      File "/path/to/venv/lib/python3.9/site-packages/pylint/__init__.py", line 24, in run_pylint
        PylintRun(sys.argv[1:])
      File "/path/to/venv/lib/python3.9/site-packages/pylint/lint/run.py", line 279, in __init__
        linter.load_plugin_modules(self._plugins)
      File "/path/to/venv/lib/python3.9/site-packages/pylint/lint/pylinter.py", line 503, in load_plugin_modules
        module = astroid.modutils.load_module_from_name(modname)
      File "/path/to/venv/lib/python3.9/site-packages/astroid/modutils.py", line 212, in load_module_from_name
        return importlib.import_module(dotted_name)
      File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
        return _bootstrap._gcd_import(name[level:], package, level)
      File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
      File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
      File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
      File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
      File "<frozen importlib._bootstrap_external>", line 790, in exec_module
      File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
      File "/path/to/venv/lib/python3.9/site-packages/pylint_quotes/__init__.py", line 4, in <module>
        from pylint_quotes import plugin, checker  # noqa: F401
      File "/path/to/venv/lib/python3.9/site-packages/pylint_quotes/plugin.py", line 5, in <module>
        from pylint_quotes.checker import StringQuoteChecker
      File "/path/to/venv/lib/python3.9/site-packages/pylint_quotes/checker.py", line 7, in <module>
        from pylint.__pkginfo__ import numversion as pylint_version
    ImportError: cannot import name 'numversion' from 'pylint.__pkginfo__' (/path/to/venv/lib/python3.9/site-packages/pylint/__pkginfo__.py)

This change also broke pylama, as reported in https://github.com/PyCQA/pylint/issues/4399, and was partially reverted by https://github.com/PyCQA/pylint/pull/4400 for pylint 2.8.1 with plans to remove it permanently in 3.0.

[What's New in Pylint 2.8](https://github.com/PyCQA/pylint/blob/pylint-2.8.1/doc/whatsnew/2.8.rst) recommends using:

```python
from importlib import metadata
metadata.metadata('pylint')
```

Thanks,
Kevin

**Comment by edaniszewski** [comment]
Thanks for filing the issue, and sorry for the delay in response and in addressing it. With the latest 0.2.2 release, I believe this should be fixed. Cllosing this out -- if the issue remains, feel free to reopen this issue or a new one.

**Comment by kevinoid** [comment]
No worries.  Thanks for looking at it @edaniszewski!

Unfortunately, I don't believe this issue is fixed.  #25, which claims to fix it, appears to [only change a `pylint_version` check in `StringQuoteChecker.get_offset`](https://github.com/edaniszewski/pylint-quotes/pull/25/files#diff-4f7dcb763479455ef151282b0e6e6958a41a64ab298aa39b6788948282a6c0cc), which is not related to this issue.  `pylint_quotes/checker.py` still imports `numversion` from `__pkginfo__` which is deprecated and is slated for removal in pylint 3.0:

https://github.com/edaniszewski/pylint-quotes/blob/4f5119f4e7b2ecb55f5706b4819a03bbdc5cb2c8/pylint_quotes/checker.py#L7

**Comment by edaniszewski** [comment]
okay, I think I got it right this time around in e9f5583 (:

will cut a new release for that. closing this issue again, but will reopen if I've messed things up again

**Comment by kevinoid** [comment]
Works for me.  Thanks @edaniszewski!
