### ISSUE TITLE
`ImportError` with release of `pylint==3.0.0`

### ISSUE THREAD

**Issue by fmigneault** [edaniszewski/pylint-quotes#29]
The following error is encountered with newer `pylint`:

```pytb
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.10.13/x64/bin/pylint", line 8, in <module>
    sys.exit(run_pylint())
  File "/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/pylint/__init__.py", line 34, in run_pylint
    PylintRun(argv or sys.argv[1:])
  File "/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/pylint/lint/run.py", line 155, in __init__
    linter.load_plugin_modules(self._plugins)
  File "/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/pylint/lint/pylinter.py", line 380, in load_plugin_modules
    module = astroid.modutils.load_module_from_name(modname)
  File "/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/astroid/modutils.py", line 194, in load_module_from_name
    module = importlib.import_module(dotted_name)
  File "/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/pylint_quotes/__init__.py", line 5, in <module>
    from pylint_quotes import checker, plugin  # noqa: F401
  File "/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/pylint_quotes/checker.py", line 8, in <module>
    from pylint.interfaces import IAstroidChecker, ITokenChecker
ImportError: cannot import name 'IAstroidChecker' from 'pylint.interfaces' (/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/pylint/interfaces.py)
```

Versions:
```
pylint 3.0.0
pylint_quotes 0.2.3
astroid 3.0.0
```

**Comment by sistlind** [comment]
See #28

**Comment by TomasChmelik** [comment]
Well, let's hope some maintainer is still alive and willing to merge the PR.
